print("How old are you?", end='')
age = input()
print("How tall are you?")
height = input()
print("How much do you weigh?", end='')
weigh = input()
print(f"so, your {age} year old, {height} tall & {weigh} heavy.")
